name: logo
on:
  push:
    branches:
      - master

jobs:
  update-logo:
    name: Retrieve JMPA logo
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout JMPA
        uses: actions/checkout@v2
        with:
          repository: jmpa-oss/jmpa-oss
          path: jmpa-oss
          token: ${{ secrets.GH_TOKEN }}

      - name: Update logo
        run: |
          # retrieve latest
          mv jmpa-oss/logo.png ./new.logo.png
          rm -rf jmpa-oss

          # compare
          old=$(cat ./logo.png)
          new=$(cat ./new.logo.png)
          if [[ "$old" != "$new" ]]; then
            echo "updating logo with latest"
            mv ./new.logo.png ./logo.png
            echo "::set-output name=PUSH::true"
          else
            echo "no changes found!"
          fi

      - name: Commit new logo?
        if: steps.generate.outputs.PUSH
        run: |
          git config user.name 'GitHub Actions'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "[skip ci] Updated logo"
          git push origin HEAD:master
