name: logo
on:
  push:
    branches:
      - master

jobs:
  retrive:
    name: Retrieve JMPA logo
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout JMPA
        uses: actions/checkout@v2
        with:
          repository: jmpa-oss/jmpa-oss
          path: jmpa-oss
          token: ${{ secrets.GH_TOKEN }}

      - name: Update logo
        run: |
          # move logo
          mv jmpa-oss/logo.png ./
          rm -rf jmpa-oss

          # commit logo
          git config user.name 'GitHub Actions'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "[skip ci] Updated logo"
          git push origin HEAD:master
